#pragma once

#include "engine/sound/BRRDecoder.h"
#include "engine/assets/AssetManager.h"
#include <array>
#include <cstdint>
#include <vector>

static constexpr int NUM_INSTRUMENTS = 35;
static constexpr int NUM_SONGS       = 72;
static constexpr int SONG_SLOTS      = 16;  // SPC RAM sample slots per song (32–47)

// Per-instrument hardware metadata from song-data.asm tables.
struct SampleMeta {
    uint8_t freqMultLo;  // SampleFreqMult lo byte (multiplier / detune base)
    uint8_t freqMultHi;  // SampleFreqMult hi byte (fine tuning)
    uint8_t adsr1;       // SampleADSR byte 0: $80 | attack[3:0] | (decay[2:0]<<4)
    uint8_t adsr2;       // SampleADSR byte 1: release[4:0] | (sustain[2:0]<<5)
};

// ---------------------------------------------------------------------------
// SampleBank
//
// Loads the 35 FF5 BRR instruments from the asset files and decodes them
// to int16 PCM once at startup, ready for the Sequencer to mix.
//
// Also loads the song_samples.dat table which maps, for each song, which
// instrument occupies each SPC sample slot.  Generated by tools/encode_song_samples.py.
// ---------------------------------------------------------------------------
class SampleBank {
public:
    SampleBank() = default;

    // Loads and decodes all instruments and the song-sample slot table.
    // Returns false on failure.
    bool load(const AssetManager& assets);

    const DecodedSample& sample(int id) const {
        return m_samples[id >= 0 && id < NUM_INSTRUMENTS ? id : 0];
    }

    const SampleMeta& meta(int id) const {
        return k_meta[id >= 0 && id < NUM_INSTRUMENTS ? id : 0];
    }

    // Returns the 0-based instrument index for the given song's k-th sample slot
    // (slot 32+k in SPC terms).  Returns 0xFF if unmapped.
    uint8_t songInstrument(int songIdx, int slotK) const;

private:
    std::array<DecodedSample, NUM_INSTRUMENTS> m_samples;

    // song_samples.dat: NUM_SONGS * SONG_SLOTS bytes (0xFF = unused).
    std::vector<uint8_t> m_songSamples;

    // Instrument metadata from song-data.asm (SampleFreqMult + SampleADSR tables)
    static const SampleMeta k_meta[NUM_INSTRUMENTS];
};
